### ISSUE TITLE
LeanDojo使用教程网页无法正常加载图片

### ISSUE THREAD

**Issue by hmyuuu** [Lean-zh/lean-zh.github.io#4]
[LeanDojo使用教程](https://www.leanprover.cn/#/tutorial/lean-dojo)
此处网页的图片无法加载，似乎是因为图片过大？（2.6MB）
![image](https://github.com/user-attachments/assets/babb8097-bab5-45ae-9d94-f148b99d65b2)

## 浏览器环境
Microsoft Edge 126.0.2592.87
Safari 17.6

**Comment by RexWzh** [comment]
多谢提醒，已更新图片 url。
